#!/usr/bin/env bash
# This script modifies /etc/hosts to map localhost to 127.0.0.2 and facebook.com to 8.8.8.8

echo "Updating the /etc/hosts file..."
{
    echo "127.0.0.2   localhost"
    echo "8.8.8.8     facebook.com"
} | sudo tee /etc/hosts > /dev/null